### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by mobreza** [CIAT-DAPA/cwr_cwrdiversity.org#1]
There seems to be a lot of PHP code where function arguments are concatenated to a String variable to form an SQL query. See the use of $genus variable in the sample code below:

```
public function getTaxaListByGenus($genus) {
    global $db;
    $query = "SELECT CWR_Scientific_Name FROM cwr_occurrences_species where taxon like '$genus%'";
    $result = $db->getAll($query);
```

Wouldn't the $genus with value 

```
    "test'; update cwr_occurrences_species set  CWR_Scientific_Name='Hahaha'; --" 
```

produce a valid SQL query:

```
   SELECT CWR_Scientific_Name FROM cwr_occurrences_species where taxon like 'test'; update cwr_occurrences_species set  CWR_Scientific_Name='Hahaha'; --'
```

and mess up the database? How are you protecting against SQL injection?

**Comment by stevensotelo** [comment]
I am going to review and fix it

**Comment by ar-mohammadi** [comment]
I have set up the website but there seem to be two issues:
1) I'm getting the following error in some parts of page

> "Warning: Illegal string offset 'id' in /var/www/cwrtest/public/wp-content/themes/yamidoo-child/index.php on line 4"

It sounds like the template is not maintained anymore
2) There are two variables in the codes : "LIB_DIR" and "WORKSPACE_DIR" referring to folders in home directory. It would be great if you could send me those.

Thanks,
Ali

**Comment by stevensotelo** [comment]
Hi Ali

1) I need more information about that point.
2) LIB_DIR = It is the absolute path in your server for the folder called "lib" in the root of this repository.
WORKSPACE_DIR=It is the absolute path in your server for the folder called "CWR-DistributionMap" in the root of this repository.

**Comment by ar-mohammadi** [comment]
Hi Steve,
For the issue (1), as we are using PHP 5.5 and the theme is optimised for earlier versions, I have modified the following:

``` php
foreach ($options as $value) {
    if (get_settings($value['id']) === FALSE) {
        $$value['id'] = $value['std'];
    } else {
        $$value['id'] = get_settings($value['id']);
    }
}
```

to 

``` php
foreach ($options as $value) {
  if (isset($value['id'])) {  // This line is added
    if (get_settings($value['id']) === FALSE) {
        $$value['id'] = $value['std'];
    } else {
        $$value['id'] = get_settings($value['id']);
    }
  }  // This line is added
}
```

in the following files:

```
wp-content/themes/yamidoo-child/footer.php
wp-content/themes/yamidoo-child/header.php
wp-content/themes/yamidoo-child/index.php
wp-content/themes/yamidoo/footer.php
wp-content/themes/yamidoo/sidebar.php
public/wp-content/themes/yamidoo/page.php
wp-content/themes/yamidoo/template-fullwidth.php
```

Additionally, I observed some other issues,
The URL for /distribution-map/ is an absolute URL and has to change (in the code or db). Can you please let me know how I can change it?

(2) I also noticed that js and css files are not loading properly. For example, when I hit http://cwrtest.croptrust.org/checklist, it wants to fetch js and css files from CWR-DistributionMap folder. I see that SMARTY constants in config.php file CWR-Checklist (e.g. SMARTY_JS_URI, SMARTY_CSS_URI) are pointing to CWR-DistributionMap folder. I believe that I have to change them to CWR-Checklist folder?

(3) There are some rewrite rules that don't look like valid. For example:

```
RewriteRule ^upload/js/(.*).js /CWR-DataUpload/themes/yamidoo-child/js/$1.js [L]
```

while CWR-DataUpload folder does not exist.

**Comment by stevensotelo** [comment]
Hi Ali
1. I recommend to you keep the same configuration in Apache while you learn more about of the application, for this case, I have enabled the following url with php info:

http://www.cwrdiversity.org/temp/aksdjfgaslhfgajsdhfavgscfsghd.php
- Maybe it was a wrong typed. The url can be changed by "/distribution-map/". You can change the url in the admin panel of the wordpress, in the left panel you can see the option Appearance->Menu, inside this page you should search the menu option called "Interactive Map" and there you rename the url.
1. It is a error of "copy and paste", the correct values in that file are: 
   define("SMARTY_ROOT_URI", 'http://www.cwrdiversity.org/CWR-Checklist');
   define("SMARTY_URL_CHECKLIST", 'http://www.cwrdiversity.org/checklist/');
   define("SMARTY_JS_URI", 'http://www.cwrdiversity.org/CWR-Checklist/themes/yamidoo-child/js');
   define("SMARTY_CSS_URI", 'http://www.cwrdiversity.org/CWR-Checklist/themes/yamidoo-child/css');
   define("SMARTY_IMG_URI", 'http://www.cwrdiversity.org/CWR-Checklist/themes/yamidoo-child/images');

I will do a commit  and fix the those values in the repository.
1. The app CWR-DataUpload was a prototype and I delete that folder from repository, you can delete that line from .htaccess

**Comment by ar-mohammadi** [comment]
Hi Steven,

(1) I forgot to mention that we are using NGINX/PHP-FPM (and no Apache/PHP). And I believe that's why we see those errors. Any other suggestions?
(2) & (3) Thanks, I did it accordingly.
