### ISSUE TITLE
CWR-Checklist configuration

### ISSUE THREAD

**Issue by ar-mohammadi** [CIAT-DAPA/cwr_cwrdiversity.org#2]
All URIs in CWR-Checklist configuration file (https://github.com/CIAT-DAPA/cwr_cwrdiversity.org/blob/master/CWR-Checklist/config/config-test.php) is pointing to CWR-DistributionMap which need to be fixed.

**Comment by stevensotelo** [comment]
With the commit aba5f86, the problem was fixed
