### ISSUE TITLE
Check list page - Back button

### ISSUE THREAD

**Issue by ar-mohammadi** [CIAT-DAPA/cwr_cwrdiversity.org#4]
Once you search for a crop in "http://www.cwrdiversity.org/checklist/" page, Back button in the bottom of the page points to "http://www.cwrdiversity.org/checklist/SMARTY_URL_CHECKLIST".

**Comment by stevensotelo** [comment]
This error has been fixed.

**Comment by ar-mohammadi** [comment]
I pulled the changes but the error is still there.

**Comment by stevensotelo** [comment]
I changed the way how the button worked, it now returns with javascript. I have commited the changes again.
